# Based on namespace from values.yaml we can define what files to put into secrets.
# Adding volume secret to avoid any confusion with envsecrets (IF any)
{{- $path := printf "namespaces/%s/config/*" .Values.namespace  }}
{{- if $path }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-volume-sec
  namespace: {{ .Values.namespace}}
  labels:
    app: {{ .Values.name }}
    chart: "{{ .Values.name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
{{ (.Files.Glob $path).AsSecrets | indent 2 }}
{{- end }}